# Default initial positions for my_arm's ros2_control fake system

initial_positions:
  arm1_arm2_joint: 0
  arm2_gripper_base_joint: 0
  base_rotating_waste_joint: 0
  gripper_base_left_gear_joint: 0
  rotating_waste_arm1_joint: 0