# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true

    joints:
      - base_rotating_waste_joint
      - rotating_waste_arm1_joint
      - arm1_arm2_joint
      - arm2_gripper_base_joint
  gripper_controller:
    type: GripperCommand
    joints:
      - gripper_base_left_gear_joint
    action_ns: gripper_cmd
    default: true